# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Define the CustomerService with the required arguments
    App\Service\CustomerService:
        arguments:
            - '@doctrine.orm.entity_manager'

    # Define the ImportCustomersCommand with the required arguments
    App\Command\ImportCustomersCommand:
        arguments:
            $CustomerSrv: '@App\Service\CustomerService'
        tags:
            - { name: console.command, command: app:import-customers }

    # Define the CustomerController with autowire and autoconfigure
    App\Controller\CustomerController:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'controller.service_arguments' }

    # Define the CustomerRepository with autowire and autoconfigure
    App\Repository\CustomerRepository:
        public: true
        autowire: true
        autoconfigure: true
        arguments: ['@doctrine.orm.entity_manager']